---
- name: Provision plex
  hosts: plex
  become: yes
  become_user: root
  any_errors_fatal: true
  roles:
    - common
    - nfs-server
    - geerlingguy.nfs
  vars:
    user: jadmin
    src: UUID=71400d7e-299a-4717-83d1-02a170e40160
    mnt_location: /mnt/jhdd
    nfs_exports: [ "/mnt/jhdd/Media *(rw,sync,no_root_squash)" ]
