---
- name: Provision plex
  hosts: plex
  become: yes
  become_user: root
  any_errors_fatal: true
  roles:
    - common
    - nfs-client
  vars:
    user: jadmin
    src: 192.168.1.254:/mnt/jhdd
    mnt_location: /home/{{ user }}/jhdd
