- name: install nfs-common
  apt:
    name: nfs-common
    state: present

- name: mount nfs
  mount:
    path: '{{ mnt_location }}'
    src: '{{ src }}'
    fstype: nfs
    opts: defaults
    passno: 2
    state: present
    