- name: apt cache updated
  apt:
    update_cache: yes
    cache_valid_time: 600
- name: apt cache purge
  apt:
    autoclean: yes
    autoremove: yes
- name: apt dist update
  apt:
    upgrade: dist
- name: Install common apps
  apt: pkg="{{item}}" state="present"
  with_items:
    - apt-transport-https
    - fail2ban
    - htop
    - vim
